import nodemailer from "nodemailer";
import sgMail from '@sendgrid/mail'
import Mailgun from 'mailgun.js'
import formData from "form-data";

sgMail.setApiKey('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');

const enviarEmailRegistro= async (token)=>{
    /*var transport = nodemailer.createTransport({
        host: "smtp.mailtrap.io",
        port: 2525,
        auth: {
          user: "07e18f1b4f7262", //example of generated by Mailtrap 
          pass: "70a62553151275" //example of generated by Mailtrap 
        }
      });
       
      var mailOptions = {
        from: 'from@example.com',
        to: 'test@example.com',
        subject: 'Test Nodemailer with Mailtrap',
        
        html: `<a href="${process.env.BACKEND_URL}/confirmar-cuenta/${token}">Recuperar cuenta</a>`,
      };
       
      transport.sendMail(mailOptions, (error, info) => {
        if (error) {
          return console.log(error);
        }
        console.log('Email sent: ' + info.response);
      });
      
    */

/*      sgMail.setApiKey(API_KEY)

      const message = {
        to: 'contrerasgomezalfonso@gmail.com',
        from: 'pruebaphpcode@gmail.com',
        subject: 'Hola desde sendGrid',
        text: 'Helloooo',
        html: '<h1>ADIOSSS</h1>',
      };

      sgMail.send(message)
        .then(response=>console.log('Email send..'))
        .catch(error=>console.log(error.message));*/
      
        //CON MAILGUN

      /*  const mailgun = new Mailgun(formData);
        const mg = mailgun.client({
          username: 'api',
          key: '54f591557a4e04f40740abe14cff7b74-ca9eeb88-6299d443',
        });
        mg.messages
          .create('sandboxab406cb3af204a36bf1866eb31cb95cd.mailgun.org', {
            from: "Mailgun Sandbox <postmaster@sandboxab406cb3af204a36bf1866eb31cb95cd.mailgun.org>",
            to: ["pruebaphpcode@gmail.com"],
            subject: "Hello",
            text: "Testing some Mailgun awesomness!",
          })
          .then(msg => console.log(msg)) // logs response data
          .catch(err => console.log(err)); // logs any error`;
          
*/


          try {
            await sgMail.send({
              to:'1923010051@untels.edu.pe',
              from:'contrerasgomezalfonso@gmail.com',
              subject: 'NodeJs Says Hello!',
              html: `<a href="${process.env.BACKEND_URL}/confirmar-cuenta/${token}">Recuperar cuenta</a>`,
            });
          } catch (error) {

            console.log(error);

            if(error.response){
              console.log(error.response.body);
            }
            
          }


};



export {
  enviarEmailRegistro
}